{% set name = "ipychart" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ec277f4b22dc503698cbaa57dd8d1e7d3c6f84d2a47212413b2e05b680660e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.18.0,<1.20.0
    - pandas >=1.0.3,<1.2.0
    - ipywidgets >=7.4.0,<8.0.0
    - pydash >=4.8.0,<5.0.0
    - scikit-learn >=0.23.2,<0.24.0
    - traitlets >=4.3.0,<5.0.0

test:
  imports:
    - ipychart

about:
  home: https://github.com/nicohlr/ipychart
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Jupyter - Chart.js bridge

  description: |
    ipychart is an ipywidget which allows to create dynamic, refined 
    and customizable charts within the famous Jupyter Notebook environment.
  doc_url: https://nicohlr.gitlab.io/ipychart/
  dev_url: https://github.com/nicohlr/ipychart

extra:
  recipe-maintainers:
    - nicohlr
