{% set name = "ipychart" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db6aca20c6c4a8d8c8713f44d7aeffa932d97dcf98f7b583f645df875aded94d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - python >=3.10
    - pip
    - jupyter-packaging
  run:
    - python
    - python >=3.10
    - ipywidgets >=8.1.3,<9.0.0
    - numpy >=2.0.1,<3.0.0
    - pandas >=2.2.2,<3.0.0
    - scikit-learn >=1.5.1,<2.0.0
    - traitlets >=5.14.3,<6.0.0
    - pydash >=8.0.3,<9.0.0

test:
  imports:
    - ipychart

about:
  home: https://github.com/nicohlr/ipychart
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Jupyter - Chart.js bridge

  description: |
    ipychart is an ipywidget which allows to create dynamic, refined 
    and customizable charts within the famous Jupyter Notebook environment.
  doc_url: https://nicohlr.gitlab.io/ipychart/
  dev_url: https://github.com/nicohlr/ipychart

extra:
  recipe-maintainers:
    - nicohlr
