{% set name = "ipychart" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2df0f8b0760c1c98062f29b2b32ad250c1ea245699b6798f78fdb9d014546425

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - python >=3.10
    - pip
    - jupyter-packaging
    - hatchling >=1.21.1
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.8.3
  run:
    - python
    - python >=3.10
    - ipywidgets >=8.1.3,<9.0.0
    - numpy >=2.0.1,<3.0.0
    - pandas >=2.2.2,<3.0.0
    - scikit-learn >=1.5.1,<2.0.0
    - traitlets >=5.14.3,<6.0.0
    - pydash >=8.0.3,<9.0.0

test:
  imports:
    - ipychart

about:
  home: https://github.com/nicohlr/ipychart
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Jupyter - Chart.js bridge

  description: |
    ipychart is an ipywidget which allows to create dynamic, refined 
    and customizable charts within the famous Jupyter Notebook environment.
  doc_url: https://nicohlr.gitlab.io/ipychart/
  dev_url: https://github.com/nicohlr/ipychart

extra:
  recipe-maintainers:
    - nicohlr
